### ISSUE TITLE
Remove \Database Facade in controller

### ISSUE THREAD

**Issue by joe-meyer** [cryophallion/C5-BoilerplateBlockType#1]
In the later versions of version 7 and going forward, you should avoid using aliases and facades wherever possible. To help with this most controller implement the `ApplicationAwareInterface`.

Instead of using `Database::connection()` in the controller, a more efficient way to do that is to use `$this->app->make('Concrete\Core\Database\DatabaseManager')->connection();`

**Comment by cryophallion** [comment]
Ok, so Korvin has set me straight on this. I'm going to go with best of both worlds and add a `getDatabase` method to the code to employ this, and also DRY it out a bit better. Please let me know if the changes make it a better starting point!

**Comment by joe-meyer** [comment]
Looks reasonable to me!
